// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IVerseScoreAggregator$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IVerseScoreAggregator";
  readonly sourceName: "contracts/interfaces/IVerseScoreAggregator.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes32","name":"appId","type":"bytes32"},{"internalType":"uint256","name":"verseId","type":"uint256"}],"name":"appScore","outputs":[{"internalType":"uint256","name":"raw","type":"uint256"},{"internalType":"uint256","name":"weighted","type":"uint256"},{"internalType":"uint16","name":"weightBps","type":"uint16"},{"internalType":"bool","name":"active","type":"bool"},{"internalType":"address","name":"scoreModel","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"verseId","type":"uint256"}],"name":"fullScore","outputs":[{"internalType":"uint256","name":"total","type":"uint256"},{"components":[{"internalType":"bytes32","name":"appId","type":"bytes32"},{"internalType":"uint256","name":"rawScore","type":"uint256"},{"internalType":"uint16","name":"weightBps","type":"uint16"},{"internalType":"uint256","name":"weightedScore","type":"uint256"},{"internalType":"bool","name":"active","type":"bool"},{"internalType":"address","name":"scoreModel","type":"address"}],"internalType":"struct IVerseScoreAggregator.AppPart[]","name":"parts","type":"tuple[]"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"verseId","type":"uint256"}],"name":"globalScore","outputs":[{"internalType":"uint256","name":"total","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"registry","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IVerseScoreAggregator.sol";
  readonly buildInfoId: "solc-0_8_28-ca11b0521c5aa8d0035de1bef353af111591fa01";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IVerseScoreAggregator"]: IVerseScoreAggregator$Type;
    ["contracts/interfaces/IVerseScoreAggregator.sol:IVerseScoreAggregator"]: IVerseScoreAggregator$Type;
  }
}