
services:
  postgres:
    image: postgres:16
    container_name: verse-postgres
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: verse
      POSTGRES_PASSWORD: verse
      POSTGRES_DB: verse_dev
    volumes:
      - verse_pg_data:/var/lib/postgresql/data

volumes:
  verse_pg_data:

