packages:
  - apps/*
  - packages/*
  - contracts/*
  - services
  - services/*

ignoredBuiltDependencies:
  - blake-hash
  - bufferutil
  - esbuild
  - keccak
  - protobufjs
  - sharp
  - unrs-resolver
  - utf-8-validate

patchedDependencies: null
