// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IScoreModel$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IScoreModel";
  readonly sourceName: "contracts/interfaces/IScoreModel.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"verseId","type":"uint256"}],"name":"scoreOf","outputs":[{"internalType":"uint256","name":"score","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IScoreModel.sol";
  readonly buildInfoId: "solc-0_8_28-303539a40135dd839c13af8bcc82f54544003c3e";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IScoreModel"]: IScoreModel$Type;
    ["contracts/interfaces/IScoreModel.sol:IScoreModel"]: IScoreModel$Type;
  }
}