/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CoreFaucet__factory } from './CoreFaucet__factory.js';
export { CoreToken__factory } from './CoreToken__factory.js';