// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface GatingLib$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "GatingLib";
  readonly sourceName: "contracts/utils/GatingLib.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea264697066735822122096692e936454a8fd225576903bebb986f18cf32ce2a77793f54a11d30e04558164736f6c634300081c0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f5ffdfea264697066735822122096692e936454a8fd225576903bebb986f18cf32ce2a77793f54a11d30e04558164736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/utils/GatingLib.sol";
  readonly buildInfoId: "solc-0_8_28-d7b1564745b5d99d6e7de74c3364c7290d21ff44";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["GatingLib"]: GatingLib$Type;
    ["contracts/utils/GatingLib.sol:GatingLib"]: GatingLib$Type;
  }
}