// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface GatingLib$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "GatingLib";
  readonly sourceName: "contracts/utils/GatingLib.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220a5849474d742dcccf73d5df3a444de3259a42fb1c950c25d4eca4d38ca4d106464736f6c634300081c0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220a5849474d742dcccf73d5df3a444de3259a42fb1c950c25d4eca4d38ca4d106464736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/utils/GatingLib.sol";
  readonly buildInfoId: "solc-0_8_28-570cd3384b7db643e9ff3ef2e56969b032cd6e54";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["GatingLib"]: GatingLib$Type;
    ["contracts/utils/GatingLib.sol:GatingLib"]: GatingLib$Type;
  }
}