// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface GatingLib$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "GatingLib";
  readonly sourceName: "contracts/utils/GatingLib.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220c8e22bc64585338f0146f21ed1d8c43c24eb49a4e03ad0806414f1e780450cc464736f6c634300081c0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220c8e22bc64585338f0146f21ed1d8c43c24eb49a4e03ad0806414f1e780450cc464736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/utils/GatingLib.sol";
  readonly buildInfoId: "solc-0_8_28-86fa94fba55064f9de317f893d55cbbfd9fee11c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["GatingLib"]: GatingLib$Type;
    ["contracts/utils/GatingLib.sol:GatingLib"]: GatingLib$Type;
  }
}