// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ScoreModelBase$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ScoreModelBase";
  readonly sourceName: "contracts/core/ScoreModelBase.sol";
  readonly abi: [{"inputs":[],"name":"appId","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"reputationHub","outputs":[{"internalType":"contract IVerseReputationHub","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"verseId","type":"uint256"}],"name":"scoreOf","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/core/ScoreModelBase.sol";
  readonly buildInfoId: "solc-0_8_28-303539a40135dd839c13af8bcc82f54544003c3e";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ScoreModelBase"]: ScoreModelBase$Type;
    ["contracts/core/ScoreModelBase.sol:ScoreModelBase"]: ScoreModelBase$Type;
  }
}