// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IVerseAppRegistry$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IVerseAppRegistry";
  readonly sourceName: "contracts/interfaces/IVerseAppRegistry.sol";
  readonly abi: [{"inputs":[],"name":"allAppIds","outputs":[{"internalType":"bytes32[]","name":"","type":"bytes32[]"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes32","name":"appId","type":"bytes32"}],"name":"appConfigOf","outputs":[{"internalType":"address","name":"writer","type":"address"},{"internalType":"address","name":"scoreModel","type":"address"},{"internalType":"uint16","name":"weightBps","type":"uint16"},{"internalType":"bool","name":"active","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes32","name":"appId","type":"bytes32"},{"internalType":"uint256","name":"verseId","type":"uint256"}],"name":"computeAppScore","outputs":[{"internalType":"uint256","name":"rawScore","type":"uint256"},{"internalType":"uint16","name":"weightBps","type":"uint16"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes32","name":"appId","type":"bytes32"}],"name":"getApp","outputs":[{"components":[{"internalType":"string","name":"name","type":"string"},{"internalType":"address","name":"writer","type":"address"},{"internalType":"address","name":"scoreModel","type":"address"},{"internalType":"uint16","name":"weightBps","type":"uint16"},{"internalType":"bool","name":"active","type":"bool"}],"internalType":"struct IVerseAppRegistry.App","name":"","type":"tuple"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes32","name":"appId","type":"bytes32"}],"name":"isActive","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes32","name":"appId","type":"bytes32"},{"internalType":"address","name":"candidate","type":"address"}],"name":"isWriter","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IVerseAppRegistry.sol";
  readonly buildInfoId: "solc-0_8_28-22a3b087098a8ffa75d7cf1f820d874c6a55db6b";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IVerseAppRegistry"]: IVerseAppRegistry$Type;
    ["contracts/interfaces/IVerseAppRegistry.sol:IVerseAppRegistry"]: IVerseAppRegistry$Type;
  }
}