// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IVerseReputationHub$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IVerseReputationHub";
  readonly sourceName: "contracts/interfaces/IVerseReputationHub.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"verseId","type":"uint256"},{"internalType":"bytes32","name":"appId","type":"bytes32"},{"internalType":"address","name":"token","type":"address"}],"name":"getActivity","outputs":[{"internalType":"uint64","name":"completed","type":"uint64"},{"internalType":"uint64","name":"cancelled","type":"uint64"},{"internalType":"uint256","name":"earned","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"verseId","type":"uint256"},{"internalType":"bytes32","name":"appId","type":"bytes32"}],"name":"getRawCounts","outputs":[{"internalType":"uint64","name":"completed","type":"uint64"},{"internalType":"uint64","name":"cancelled","type":"uint64"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"verseId","type":"uint256"}],"name":"logCancelled","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"verseId","type":"uint256"},{"internalType":"address","name":"token","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"logCompleted","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IVerseReputationHub.sol";
  readonly buildInfoId: "solc-0_8_28-86fa94fba55064f9de317f893d55cbbfd9fee11c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IVerseReputationHub"]: IVerseReputationHub$Type;
    ["contracts/interfaces/IVerseReputationHub.sol:IVerseReputationHub"]: IVerseReputationHub$Type;
  }
}